---
version: '2.0'
services:
  recursor:
    container_name: recursor
    build:
      context: .
      dockerfile: Dockerfile-recursor
    environment:
      - PDNS_RECURSOR_API_KEY
    ports:
      - "2053:53"
      - "2053:53/udp"
      - "8882:8082"
    volumes:
      - /etc/powerdns/:/etc/powerdns

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: Dockerfile-auth
    environment:
      - PDNS_AUTH_API_KEY
    ports:
      - "1053:53"
      - "1053:53/udp"
      - "8881:8081"
    volumes:
      - /etc/powerdns/:/etc/powerdns
